services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server:latest
    container_name: valheim-server
    restart: unless-stopped
    cap_add:
      - sys_nice
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ:-Etc/UTC}
      SERVER_NAME: ${SERVER_NAME}
      WORLD_NAME: ${WORLD_NAME}
      SERVER_PASS: ${SERVER_PASS}
      SERVER_PUBLIC: "false"
      CROSSPLAY: "false"
      ADMINLIST_IDS: ${ADMINLIST_IDS:-}
      BEPINEX: "${BEPINEX:-false}"
      BACKUPS: "true"
      BACKUPS_CRON: "5 * * * *"
      BACKUPS_MAX_AGE: 7
      BACKUPS_MAX_COUNT: 0
      BACKUPS_ZIP: "true"
      UPDATE_CRON: ""
      UPDATE_IF_IDLE: "true"
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
